<?php

return [
    'dashboard' => [
        'view' => 'View Dashboard',
    ],
    'tasks' => [
        'my_tasks' => 'View My Tasks',
        'view' => 'View Tasks',
        'create' => 'Create Task',
        'edit' => 'Edit Task',
        'delete' => 'Delete Task',
        'todo' => 'View My To-Do List',
        'activity' => 'View My Task Activity',
        'board' => 'View Task Board',
        'calendar' => 'View Calendar',
        'gantt' => 'View Gantt Chart',
    ],
    'projects' => [
        'view' => 'View Projects',
        'create' => 'Create Project',
        'edit' => 'Edit Project',
        'delete' => 'Delete Project',
    ],
    'tickets' => [
        'view' => 'View Tickets',
        'view_all' => 'View All Tickets',
        'create' => 'Create Ticket',
        'edit' => 'Edit Ticket',
        'delete' => 'Delete Ticket',
        'reply' => 'Reply to Ticket',
        'assign' => 'Assign Ticket',
    ],
    'clients' => [
        'view' => 'View Clients',
        'create' => 'Create Client',
        'edit' => 'Edit Client',
        'delete' => 'Delete Client',
    ],
    'chat' => [
        'view' => 'Access Team Chat',
        'create_staff_group' => 'Create Staff Group',
        'create_client_group' => 'Create Client Group',
    ],
    'users' => [
        'view' => 'View Users',
        'create' => 'Create User',
        'edit' => 'Edit User',
        'delete' => 'Delete User',
        'approve' => 'Approve/Disapprove User',
    ],
    'roles' => [
        'view' => 'View Roles',
        'create' => 'Create Role',
        'edit' => 'Edit Role',
        'delete' => 'Delete Role',
    ],
    'settings' => [
        'view' => 'View Settings',
        'edit' => 'Edit Settings',
    ],
    'hr' => [
        'view' => 'View HR Overview & Dashboard',
        'manage' => 'Manage HR Settings & System Policies',
        'attendance_settings' => 'Manage Attendance & Office Rules',
        'shift_rules' => 'Manage Shift & Auto-Stop Timer Rules',
        'leave_requests' => 'Manage Leave Requests & Approvals',
        'work_reports' => 'Review Daily Work Reports',
        'timesheets' => 'Audit & Export Monthly Timesheets',
        'staff' => 'Manage Staff & Employee Profiles',
        'roles' => 'Manage Roles & Access Permissions',
    ],
    'attendance' => [
        'view' => 'View Attendance',
        'create' => 'Create Attendance',
        'update' => 'Update Attendance',
        'delete' => 'Delete Attendance',
        'punch' => 'Punch In/Out Attendance',
        'submit' => 'Submit Daily Attendance',
        'approve' => 'Approve Daily Attendance',
        'reject' => 'Reject Daily Attendance',
        'report' => 'View Attendance Reports',
        'export' => 'Export Attendance Reports',
        'manage' => 'Manage Attendance & Settings',
        'dashboard_overview' => 'View All Users Dashboard Stats',
        'daily' => 'View/Edit Daily Attendance',
        'monthly' => 'View Monthly Attendance',
        'calendar_all' => 'View All Users Calendars',
        'requests_manage' => 'Manage All Leave Requests',
        'reports' => 'View Attendance Reports',
        'settings' => 'Manage Attendance Settings',
    ],
    'meetings' => [
        'view' => 'View Meetings',
        'create' => 'Create/Schedule Meeting',
        'join' => 'Join Meeting/Call',
        'cancel' => 'Cancel Meeting',
        'delete' => 'Delete Meeting History',
    ],
];
